export default {
    LOAD_CUSTOMER: 'LOAD_CUSTOMER',
    LOAD_SUCESS: 'LOAD_SUCESS',
    LOAD_FAIL: 'LOAD_FAIL',
    SET_LOADING_INDICATOR: 'SET_LOADING_INDICATOR',
    ADD_CUSTOMER: 'ADD_CUSTOMER',
    SET_INIT_DATA: 'SET_INIT_DATA',
    SEARCH: 'SEARCH',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER',
    CHANGE_CUSTOMER_STATUS: 'CHANGE_CUSTOMER_STATUS'
}